# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labApp.Departments', verbose_name='aaa'),
        ),
    ]
